# Generated by Django 2.2.4 on 2019-08-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='OwnerType',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
