# Generated by Django 2.2.4 on 2019-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=32)),
                ('Menu', models.CharField(max_length=32)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=10)),
            ],
        ),
    ]
