# Generated by Django 2.2.4 on 2019-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='Latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='Longitude',
            field=models.FloatField(default=None),
        ),
    ]
