# Generated by Django 2.2.4 on 2019-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190823_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=32)),
                ('StoreAddress', models.CharField(max_length=32)),
                ('StorePhone', models.CharField(max_length=13)),
                ('Latitude', models.FloatField(default=None)),
                ('Longitude', models.FloatField(default=None)),
            ],
        ),
    ]
