# Generated by Django 2.2.4 on 2019-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='Foodurl',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
