# Generated by Django 2.2.4 on 2019-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodmenu_foodurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='Foodurl',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
