# Generated by Django 2.1.7 on 2019-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190828_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessertmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=32)),
                ('Menu', models.CharField(max_length=32)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=10)),
                ('Latitude', models.FloatField(default=None)),
                ('Longitude', models.FloatField(default=None)),
                ('Foodurl', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
