# Generated by Django 2.1.7 on 2019-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_dessertmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertmenu',
            name='Foodurl',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
