# Generated by Django 2.1.7 on 2019-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20190910_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertmenu',
            name='Foodurl',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
